// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rasta.ProjectManagment.Infrastructure.Persistence;

#nullable disable

namespace Rasta.ProjectManagment.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.BasicInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("MeasureUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MeasureUnitId");

                    b.HasIndex("ParentId");

                    b.ToTable("BasicInformations");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.BasicInformationProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasicInformationId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BasicInformationId");

                    b.HasIndex("PropertyId");

                    b.ToTable("BasicInformationProperties");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.FinancialStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BalancedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("BalancedIntegratedApproved")
                        .HasColumnType("bigint");

                    b.Property<long>("BalancedPeriodApproved")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("IntegratedApproved")
                        .HasColumnType("bigint");

                    b.Property<long>("IntegratedSent")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<short>("OperationMonth")
                        .HasColumnType("smallint");

                    b.Property<int>("OperationYear")
                        .HasColumnType("int");

                    b.Property<long>("PeriodApproved")
                        .HasColumnType("bigint");

                    b.Property<long>("PeriodSent")
                        .HasColumnType("bigint");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FinancialStatement", (string)null);
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.LookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LookUps");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.MeasureUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("MeasureUnits");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.MeasureUnitMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MeasureUnitFromId")
                        .HasColumnType("int");

                    b.Property<int>("MeasureUnitToId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MeasureUnitFromId");

                    b.HasIndex("MeasureUnitToId");

                    b.ToTable("MeasureUnitMaps");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BlockCount")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ContractAmount")
                        .HasPrecision(36, 2)
                        .HasColumnType("decimal(36,2)");

                    b.Property<long?>("ContractBasisIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EndContractDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FloorCount")
                        .HasColumnType("int");

                    b.Property<bool?>("HasBuyPlan")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasCostBudjet")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasExecutionPlan")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasGroundFloor")
                        .HasColumnType("bit");

                    b.Property<int>("InfrastructureArea")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("LandscapeArea")
                        .HasColumnType("int");

                    b.Property<int?>("NegativeFloorCount")
                        .HasColumnType("int");

                    b.Property<int?>("PositiveFloorCount")
                        .HasColumnType("int");

                    b.Property<string>("ProjectManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProjectTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartContractDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Supervisor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectTypeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectAccidentDailyReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccidentEffect")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("AccidentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("DamageAmount")
                        .HasColumnType("float");

                    b.Property<int?>("DaysLostCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("AccidentTypeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectAccidentDailyReports");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectCulprits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CulpritPercent")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("JobTitleId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProjectCulprits");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectExecutionDailyReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ActivityTime")
                        .HasColumnType("int");

                    b.Property<string>("BlockNo")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MainOperation")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Persons")
                        .HasMaxLength(1024)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SubContractorName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubOperation")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalCumulativeWorkTime")
                        .HasColumnType("int");

                    b.Property<int>("TotalWorkTime")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ZoneNo")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectExecutionDailyReports");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectGuestDailyReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EnterTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExitTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("VisitorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectGuestDailyReports");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectMachineryDailyReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MachineryEquipmentDescription")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("NeedRepair")
                        .HasColumnType("bit");

                    b.Property<string>("Ownership")
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Total")
                        .HasPrecision(36)
                        .HasColumnType("decimal(36,0)");

                    b.Property<int>("WorkingHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMachineryDailyReports");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectManpowerDailyReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDirect")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Shift1")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Shift2")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Shift3")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubContractorName")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Total")
                        .HasPrecision(36)
                        .HasColumnType("decimal(36,0)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectManpowerDailyReports");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectMaterialsDailyReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("ImportAmount")
                        .HasColumnType("float");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaterialsDescription")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<string>("UsePlace")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UnitId");

                    b.ToTable("ProjectMaterialsDailyReports");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectProblemDailyReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProblemsClassifications")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectProblemDailyReports");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectRepairDailyReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<decimal?>("EstimateInitialCost")
                        .HasPrecision(36)
                        .HasColumnType("decimal(36,0)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RepairPlace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RepairStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectRepairDailyReports");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("projectTypes");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectTypeRatio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectTypeId")
                        .HasColumnType("int");

                    b.Property<int>("WFBPercentage")
                        .HasColumnType("int");

                    b.Property<int>("WFTPercentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectTypeId");

                    b.ToTable("ProjectTypeRatios");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ProjectUsers", (string)null);
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectWeek", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPlan")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WeekCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectWeekes");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectWorkBreakdown", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BaselineCost")
                        .HasPrecision(36)
                        .HasColumnType("decimal(36,0)");

                    b.Property<decimal?>("Budjet")
                        .HasPrecision(36)
                        .HasColumnType("decimal(36,0)");

                    b.Property<decimal?>("CPI")
                        .HasPrecision(36)
                        .HasColumnType("decimal(36,0)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CurrentTaskId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLastNode")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("LastStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<int?>("ParentTaskId")
                        .HasColumnType("int");

                    b.Property<string>("Predecessors")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SPI")
                        .HasPrecision(36)
                        .HasColumnType("decimal(36,0)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Successors")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("WeightFactor")
                        .HasColumnType("float");

                    b.Property<double?>("WeightFactorBudject")
                        .HasColumnType("float");

                    b.Property<double?>("WeightFactorTime")
                        .HasColumnType("float");

                    b.Property<string>("WorkBreakdownStructureCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkBreakdownStructureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectWorkBreakdowns");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectWorkBreakdownHistoryWork", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ACB")
                        .HasPrecision(36)
                        .HasColumnType("decimal(36,0)");

                    b.Property<double?>("ActualCompleteProgressPercentage")
                        .HasColumnType("float");

                    b.Property<double?>("ActualWeightProgressPercentage")
                        .HasColumnType("float");

                    b.Property<decimal?>("CV")
                        .HasPrecision(36)
                        .HasColumnType("decimal(36,0)");

                    b.Property<double?>("CumulativeActualCompleteProgressPercentage")
                        .HasColumnType("float");

                    b.Property<double?>("CumulativePlanCompleteProgressPercentage")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EV")
                        .HasPrecision(36)
                        .HasColumnType("decimal(36,0)");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PV")
                        .HasPrecision(36)
                        .HasColumnType("decimal(36,0)");

                    b.Property<double?>("PlanCompleteProgressPercentage")
                        .HasColumnType("float");

                    b.Property<double?>("PlanCumulativePercentage")
                        .HasColumnType("float");

                    b.Property<double?>("PlanPercentage")
                        .HasColumnType("float");

                    b.Property<double?>("PlanWeightProgressPercentage")
                        .HasColumnType("float");

                    b.Property<long>("ProjectWeekId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProjectWorkBreakdownId")
                        .HasColumnType("bigint");

                    b.Property<double?>("RealCumulativePercentage")
                        .HasColumnType("float");

                    b.Property<double?>("RealPercentage")
                        .HasColumnType("float");

                    b.Property<decimal?>("SV")
                        .HasPrecision(36)
                        .HasColumnType("decimal(36,0)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectWeekId");

                    b.HasIndex("ProjectWorkBreakdownId");

                    b.ToTable("ProjectWorkBreakdownHistoryWorks");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.SP_GetSummaryLevel3VM", b =>
                {
                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PlanPrecentage")
                        .HasColumnType("float");

                    b.Property<double?>("RealPrecentage")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SP_GetSummaryLevel3VMs");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.View_Culprits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CulpritPercent")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobTitleId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("View_Culprits", (string)null);
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.View_ProjectUsers", b =>
                {
                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("BranchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("View_ProjectUsers");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.BasicInformation", b =>
                {
                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.MeasureUnit", "MeasureUnit")
                        .WithMany()
                        .HasForeignKey("MeasureUnitId");

                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.BasicInformation", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("MeasureUnit");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.BasicInformationProperty", b =>
                {
                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.BasicInformation", "BasicInformation")
                        .WithMany("BasicInformationProperties")
                        .HasForeignKey("BasicInformationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.Property", "Property")
                        .WithMany("BasicInformationProperties")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BasicInformation");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.MeasureUnitMap", b =>
                {
                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.MeasureUnit", "MeasureUnitFrom")
                        .WithMany("MeasureUnitFroms")
                        .HasForeignKey("MeasureUnitFromId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.MeasureUnit", "MeasureUnitTo")
                        .WithMany("MeasureUnitTos")
                        .HasForeignKey("MeasureUnitToId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MeasureUnitFrom");

                    b.Navigation("MeasureUnitTo");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.Project", b =>
                {
                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.ProjectType", "ProjectType")
                        .WithMany()
                        .HasForeignKey("ProjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectType");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectAccidentDailyReport", b =>
                {
                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.LookUp", "AccidentType")
                        .WithMany()
                        .HasForeignKey("AccidentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.Project", "Project")
                        .WithMany("ProjectAccidentDailyReports")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AccidentType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectExecutionDailyReport", b =>
                {
                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.Project", "Project")
                        .WithMany("ProjectExecutionDailyReports")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectGuestDailyReport", b =>
                {
                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.Project", "Project")
                        .WithMany("ProjectGuestDailyReports")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectMachineryDailyReport", b =>
                {
                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.Project", "Project")
                        .WithMany("ProjectMachineryDailyReports")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectManpowerDailyReport", b =>
                {
                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.Project", "Project")
                        .WithMany("ProjectManpowerDailyReports")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectMaterialsDailyReport", b =>
                {
                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.Project", "Project")
                        .WithMany("ProjectMaterialsDailyReports")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.MeasureUnit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectProblemDailyReport", b =>
                {
                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.Project", "Project")
                        .WithMany("ProjectProblemDailyReports")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectRepairDailyReport", b =>
                {
                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.Project", "Project")
                        .WithMany("ProjectRepairDailyReports")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectTypeRatio", b =>
                {
                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.ProjectType", "ProjectType")
                        .WithMany("ProjectTypeRatios")
                        .HasForeignKey("ProjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectType");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectWeek", b =>
                {
                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.Project", "Project")
                        .WithMany("ProjectWeeks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectWorkBreakdown", b =>
                {
                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectWorkBreakdownHistoryWork", b =>
                {
                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.ProjectWeek", "ProjectWeek")
                        .WithMany("ProjectWorkBreakdownHistoryWorks")
                        .HasForeignKey("ProjectWeekId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Rasta.ProjectManagment.Domain.Entities.ProjectWorkBreakdown", "ProjectWorkBreakdown")
                        .WithMany("ProjectWorkBreakdownHistories")
                        .HasForeignKey("ProjectWorkBreakdownId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ProjectWeek");

                    b.Navigation("ProjectWorkBreakdown");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.BasicInformation", b =>
                {
                    b.Navigation("BasicInformationProperties");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.MeasureUnit", b =>
                {
                    b.Navigation("MeasureUnitFroms");

                    b.Navigation("MeasureUnitTos");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectAccidentDailyReports");

                    b.Navigation("ProjectExecutionDailyReports");

                    b.Navigation("ProjectGuestDailyReports");

                    b.Navigation("ProjectMachineryDailyReports");

                    b.Navigation("ProjectManpowerDailyReports");

                    b.Navigation("ProjectMaterialsDailyReports");

                    b.Navigation("ProjectProblemDailyReports");

                    b.Navigation("ProjectRepairDailyReports");

                    b.Navigation("ProjectWeeks");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectType", b =>
                {
                    b.Navigation("ProjectTypeRatios");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectWeek", b =>
                {
                    b.Navigation("ProjectWorkBreakdownHistoryWorks");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.ProjectWorkBreakdown", b =>
                {
                    b.Navigation("ProjectWorkBreakdownHistories");
                });

            modelBuilder.Entity("Rasta.ProjectManagment.Domain.Entities.Property", b =>
                {
                    b.Navigation("BasicInformationProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
